name: Build and Push Devcontainer Image (Pre-Production)
on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write
  actions: read
  id-token: write
env:
  IMAGE_NAME: ghcr.io/beaniezombie/zombiekit-devcontainer
  VERSION: dev
jobs:
  build-amd64:
    if: github.repository == 'BeanieZombie/zombiekit-devcontainer'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: image=moby/buildkit:latest
          buildkitd-flags: --debug
          name: build-amd64-builder
      - name: Trivy Scan (ubuntu:jammy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ubuntu:jammy'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'
          scanners: 'vuln'
      - name: Clean up previous image
        run: docker rmi ${{ env.IMAGE_NAME }}:dev-amd64 || true
      - name: Build & Push Docker Image (AMD64)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}:dev-amd64
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cache-amd64
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:cache-amd64,mode=max
      - name: Verify Image Push to GHCR
        run: |
          for i in {1..5}; do
            docker manifest inspect ${{ env.IMAGE_NAME }}:dev-amd64 && break || sleep 5
          done || {
            echo "::error::dev-amd64 not found in GHCR. Check previous step for push failure."; exit 1;
          }

  build-arm64:
    if: github.repository == 'BeanieZombie/zombiekit-devcontainer'
    runs-on: [self-hosted, linux, ARM64]
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Docker + Buildx
        run: |
          docker info || exit 1
          docker system info || exit 1
          df -h || exit 1
          free -h || exit 1
          docker buildx version || exit 1
          docker buildx inspect || exit 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: image=moby/buildkit:latest
          buildkitd-flags: --debug
          name: build-arm64-builder
      - name: Set up QEMU with Retry
        run: |
          for i in {1..3}; do
            docker run --rm --privileged tonistiigi/binfmt:latest --install all && break || {
              EXIT_CODE=$?
              if [ $EXIT_CODE -eq 125 ]; then
                break
              fi
              sleep 5
            }
          done || exit 1
      - name: Trivy Scan (ubuntu:jammy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ubuntu:jammy'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'
          scanners: 'vuln'
      - name: Clean up previous image
        run: docker rmi ${{ env.IMAGE_NAME }}:dev-arm64 || true
      - name: Build & Push Docker Image (ARM64)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ${{ env.IMAGE_NAME }}:dev-arm64
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cache-arm64
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:cache-arm64,mode=max
      - name: Verify Image Push to GHCR
        run: |
          for i in {1..5}; do
            docker manifest inspect ${{ env.IMAGE_NAME }}:dev-arm64 && break || sleep 5
          done || {
            echo "::error::dev-arm64 not found in GHCR. Check previous step for push failure."; exit 1;
          }

  combine-images:
    needs: [build-amd64, build-arm64]
    if: github.repository == 'BeanieZombie/zombiekit-devcontainer'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install jq (for debugging)
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: image=moby/buildkit:latest
          buildkitd-flags: --debug
          name: combine-images-builder
      - name: Set up QEMU with Retry
        run: |
          for i in {1..3}; do
            docker run --rm --privileged tonistiigi/binfmt:latest --install all && break || {
              EXIT_CODE=$?
              if [ $EXIT_CODE -eq 125 ]; then
                break
              fi
              sleep 5
            }
          done || exit 1
      - name: Check Docker Info
        run: |
          docker info || exit 1
          docker ps -a || exit 1
          docker images || exit 1
          docker version || exit 1
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check GHCR Availability
        run: curl -sI https://ghcr.io || exit 1
      - name: Verify Architecture Manifests Exist
        run: |
          docker manifest inspect ${{ env.IMAGE_NAME }}:dev-amd64 || {
            echo "::error::Missing dev-amd64 image. Build job may have failed."; exit 1;
          }
          docker manifest inspect ${{ env.IMAGE_NAME }}:dev-arm64 || {
            echo "::error::Missing dev-arm64 image. Build job may have failed."; exit 1;
          }
      - name: Pull Architecture Images with Retry
        run: |
          for i in {1..5}; do
            docker pull ${{ env.IMAGE_NAME }}:dev-amd64 && break || sleep 10
          done || {
            echo "::error::Failed to pull dev-amd64 after retries. Check build-amd64 logs."; exit 1;
          }
          for i in {1..5}; do
            docker pull ${{ env.IMAGE_NAME }}:dev-arm64 && break || sleep 10
          done || {
            echo "::error::Failed to pull dev-arm64 after retries. Check build-arm64 logs."; exit 1;
          }
      - name: Pre-Check Images Exist in GHCR
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://ghcr.io/v2/beaniezombie/zombiekit-devcontainer/manifests/dev-amd64 | jq .mediaType || {
              echo "::error::Missing dev-amd64 manifest in registry. Build may have failed."; exit 1;
            }
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://ghcr.io/v2/beaniezombie/zombiekit-devcontainer/manifests/dev-arm64 | jq .mediaType || {
              echo "::error::Missing dev-arm64 manifest in registry. Build may have failed."; exit 1;
            }
      - name: Verify Architecture Images in GHCR
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:dev-amd64 || {
            echo "::error::Failed to verify dev-amd64 image in GHCR."; exit 1;
          }
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:dev-arm64 || {
            echo "::error::Failed to verify dev-arm64 image in GHCR."; exit 1;
          }
      - name: List Images and Verify Registry State
        run: |
          docker images
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://ghcr.io/v2/beaniezombie/zombiekit-devcontainer/tags/list | jq
      - name: Create & Push Multi-Arch Manifest (:dev)
        run: |
          docker manifest create ${{ env.IMAGE_NAME }}:dev \
            --amend ${{ env.IMAGE_NAME }}:dev-amd64 \
            --amend ${{ env.IMAGE_NAME }}:dev-arm64 || exit 1
          for i in {1..5}; do
            docker manifest push --purge ${{ env.IMAGE_NAME }}:dev && break || sleep 10
          done || exit 1
      - name: Create & Push Multi-Arch Manifest (:latest)
        run: |
          docker manifest create ${{ env.IMAGE_NAME }}:latest \
            --amend ${{ env.IMAGE_NAME }}:dev-amd64 \
            --amend ${{ env.IMAGE_NAME }}:dev-arm64 || exit 1
          for i in {1..5}; do
            docker manifest push --purge ${{ env.IMAGE_NAME }}:latest && break || sleep 10
          done || exit 1
      - name: Log Dev Visibility
        run: echo "::notice::Container published publicly as :dev and :latest for testing only – not production ready."
      - name: Ensure Container is Public
        run: gh api --method PATCH /user/packages/container/zombiekit-devcontainer/visibility -f visibility=public
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Warn Not Production-Ready
        run: echo "::warning::This image is public for testing and CI workflows only. DO NOT use in production environments."