name: Build and Push Devcontainer Image
on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write  # Needed to push to ghcr.io
jobs:
  build-amd64:
    if: github.event_name == 'push' && github.repository == 'BeanieZombie/zombiekit-devcontainer'
    runs-on: ubuntu-jammy  # Use Ubuntu 22.04 LTS (Jammy Jellyfish) for consistency with base image
    timeout-minutes: 120  # Increase timeout to 120 minutes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Debug PATH and Docker
        run: |
          echo "PATH: $PATH"
          docker --version || { echo "Docker not found."; exit 1; }

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug TARGETPLATFORM
        run: |
          echo "Platforms to build: linux/amd64"

      - name: Scan base image for vulnerabilities (Ubuntu:jammy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ubuntu:jammy'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'  # Allow the build to continue despite vulnerabilities
          scanners: 'vuln'  # Use Docker for scanning, avoid containerd/podman

      - name: Build and push Docker image (AMD64)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ghcr.io/beaniezombie/zombiekit-devcontainer:amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max,key=${{ github.sha }}-amd64
          progress: plain  # Ensure frequent output to prevent timeout

  build-arm64:
    if: github.event_name == 'push' && github.repository == 'BeanieZombie/zombiekit-devcontainer'
    runs-on: [self-hosted, linux, ARM64]  # Requires a self-hosted ARM64 runner with these labels
    timeout-minutes: 120  # Increase timeout to 120 minutes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug PATH and Docker
        run: |
          echo "PATH: $PATH"
          docker --version || { echo "Docker not found."; exit 1; }

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug TARGETPLATFORM
        run: |
          echo "Platforms to build: linux/arm64"

      - name: Scan base image for vulnerabilities (Ubuntu:jammy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ubuntu:jammy'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'  # Allow the build to continue despite vulnerabilities
          scanners: 'vuln'  # Use Docker for scanning, avoid containerd/podman

      - name: Build and push Docker image (ARM64)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ghcr.io/beaniezombie/zombiekit-devcontainer:arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max,key=${{ github.sha }}-arm64
          progress: plain  # Ensure frequent output to prevent timeout

  combine-images:
    needs: [build-amd64, build-arm64]
    if: github.event_name == 'push' && github.repository == 'BeanieZombie/zombiekit-devcontainer'
    runs-on: ubuntu-jammy  # Use Ubuntu 22.04 LTS (Jammy Jellyfish) for consistency with base image
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug login
        run: |
          echo "Verifying login to GHCR..."
          docker pull ghcr.io/beaniezombie/zombiekit-devcontainer:amd64 || echo "Failed to pull AMD64 image"
          docker pull ghcr.io/beaniezombie/zombiekit-devcontainer:arm64 || echo "Failed to pull ARM64 image"

      - name: Create manifest
        run: |
          docker manifest create ghcr.io/beaniezombie/zombiekit-devcontainer:latest \
            --amend ghcr.io/beaniezombie/zombiekit-devcontainer:amd64 \
            --amend ghcr.io/beaniezombie/zombiekit-devcontainer:arm64

      - name: Debug manifest creation
        run: |
          echo "Inspecting created manifest..."
          docker manifest inspect ghcr.io/beaniezombie/zombiekit-devcontainer:latest || { echo "Manifest creation failed."; exit 1; }

      - name: Push manifest
        run: |
          docker manifest push --purge ghcr.io/beaniezombie/zombiekit-devcontainer:latest